### ISSUE TITLE
Unnecessary parameter

### ISSUE THREAD

**Issue by Blightwidow** [AlbertWhite/apollo-fullstack-todolist#1]
Usually we try to minimize the number of argments on Mutation. Here, in a production environment where there is a DB behind, you wouldn't need the userId

https://github.com/AlbertWhite/apollo-fullstack-todolist/blob/0a35b32b4a05ee20551a8fea853a3a375562bb5d/server/src/index.ts#L15

**Comment by AlbertWhite** [comment]
I understand the point. Thank you for the response.
Like you said, in real DB behind, every todo has its unique ID so we don't need to identify the userID to get the todo.

Another problem here, is every todo is associated with a user. The data structure is like this 
```
type User {
  id: ID!
  name: String!
  todos: [Todo]
}
```

So if I want to update a todo, I also want to know which user does the todo belongs to, and the userId should be in the query reponse for the client to rerender the app.

I think I understand your point, that is **we can get UserId for a Todo by querying from the database on the server side so we don't need to pass UserId by mutation**.  It is preferred to pass less parameter in a mutation, and make query on server side with the DB. Am I right ?  :)
