### ISSUE TITLE
Try to avoid any

### ISSUE THREAD

**Issue by Blightwidow** [AlbertWhite/apollo-fullstack-todolist#2]
Usually not the best practice to use any, escpecially when you are sure of the type of the value due to GQL validation. You could create TS types that mirror the GQL types (probably even generate the TS types directly from GQL)

https://github.com/AlbertWhite/apollo-fullstack-todolist/blob/0a35b32b4a05ee20551a8fea853a3a375562bb5d/server/src/index.ts#L69

**Comment by AlbertWhite** [comment]
It is a very good point. Like you said, we should create TS types on Client side that mirror the GQL types in Server side.

The 'any' here is the variable for useMutation, and I found a [tutorial](https://www.apollographql.com/docs/react/development-testing/static-typing/#usemutation) about adding types for useQuery and useMutation in ApolloClient. 

I don't know whether we have to create two times the same Interface between Server and Client for variables in Hooks. There should be a better solution.

**Comment by AlbertWhite** [comment]
I made a commit to remove 'any' types, but with a heavy solution: I rewrite all the types on server side. We keep this issue opened for searching for a better solution.
